name: 'Auto Issue Bot'
description: "Disallow closing of an issue if any of it's dependents are still open"
author: "Vat Raghavan <machinshin@gmail.com>"
inputs:
  repo-token:
    description: Repository token 
    required: true
outputs:
  blocking_issues:
    description: List of issues this one is dependent on
runs:
  using: 'node12'
  main: 'dist/index.js'

